import React from 'react';
import {fireEvent, render, screen, waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import XMarketingAdmin from '@/app/admin/x-marketing/components/x-marketing-admin';
import {XMarketingAdminService as api} from '@/app/services/admin/x-marketing';
jest.mock('@/app/services/admin/x-marketing',()=>({XMarketingAdminService:{getDashboard:jest.fn(),getRateLimits:jest.fn(),getCollectedPosts:jest.fn(),getReplyCandidates:jest.fn(),getPosts:jest.fn(),getActions:jest.fn(),getSettings:jest.fn(),collect:jest.fn(),generateReplyCandidate:jest.fn(),approveReplyCandidate:jest.fn(),rejectReplyCandidate:jest.fn(),updateSettings:jest.fn()}}));
beforeEach(()=>{
 jest.clearAllMocks();
 (api.getDashboard as jest.Mock).mockResolvedValue({collected_count:12});
 (api.getRateLimits as jest.Mock).mockResolvedValue([{id:'rate',endpoint:'GET /search',remaining_count:4,limit_count:10}]);
 (api.getCollectedPosts as jest.Mock).mockResolvedValue({data:{items:[{id:'post',username:'author',textOriginal:'原文',textKo:'원문',url:'javascript:alert(1)'}]}});
 (api.getReplyCandidates as jest.Mock).mockResolvedValue({items:[{id:'candidate',ja_text:'元',edited_ja_text:'編集済み',edited_ko_meaning:'편집한 의미',target_url:'https://x.com/author/status/1'}]});
 (api.getSettings as jest.Mock).mockResolvedValue({collection_queries:[{query:'既存',enabled:true,priority:20}]});
 (api.updateSettings as jest.Mock).mockResolvedValue({});
 (api.collect as jest.Mock).mockResolvedValue({});
 (api.generateReplyCandidate as jest.Mock).mockResolvedValue({});
 (api.approveReplyCandidate as jest.Mock).mockResolvedValue({});
 (api.rejectReplyCandidate as jest.Mock).mockResolvedValue({});
});
it('retains route navigation, source fallbacks and manual collection payload; exposes failed candidate generation',async()=>{
 const user=userEvent.setup();render(<XMarketingAdmin initialView="collected-posts"/>);
 await screen.findByText('原文');
 expect(screen.getByText('원문')).toBeTruthy();
 expect(screen.queryByRole('link',{name:'X 열기'})).toBeNull();
 expect(screen.getByRole('link',{name:'수집 게시글'}).getAttribute('aria-current')).toBe('page');
 expect(screen.getByRole('link',{name:'설정'}).getAttribute('href')).toBe('/admin/x-marketing/settings');
 await user.type(screen.getByRole('textbox',{name:'검색/수집 쿼리'}),'韓国');
 await waitFor(()=>expect((screen.getByRole('button',{name:'수동 수집 실행'}) as HTMLButtonElement).disabled).toBe(false));
 await user.click(screen.getByRole('button',{name:'수동 수집 실행'}));
 await waitFor(()=>expect(api.collect).toHaveBeenCalledWith({query:'韓国',priority:100}));
 (api.generateReplyCandidate as jest.Mock).mockRejectedValueOnce(new Error('생성 오류'));
 await user.click(screen.getByRole('button',{name:'후보 생성'}));
 await screen.findByRole('alert');
 expect(api.generateReplyCandidate).toHaveBeenCalledWith('post');
 expect((screen.getByRole('button',{name:'후보 생성'}) as HTMLButtonElement).disabled).toBe(false);
});
it('preserves edited candidate content, approval/rejection identities and safe external links',async()=>{
 const user=userEvent.setup();render(<XMarketingAdmin initialView="reply-candidates"/>);
 await screen.findByText('編集済み');expect(screen.getByText('편집한 의미')).toBeTruthy();
 expect(screen.getByRole('link',{name:'X 열기'}).getAttribute('rel')).toBe('noopener noreferrer');
 await user.click(screen.getByRole('button',{name:'승인'}));
 await waitFor(()=>expect(api.approveReplyCandidate).toHaveBeenCalledWith('candidate'));
 await waitFor(()=>expect((screen.getByRole('button',{name:'거절'}) as HTMLButtonElement).disabled).toBe(false));
 await user.click(screen.getByRole('button',{name:'거절'}));
 await waitFor(()=>expect(api.rejectReplyCandidate).toHaveBeenCalledWith('candidate','운영자 거절'));
});
it('keeps focus while editing query text and saves actual switch/priority/add/delete values',async()=>{
 const user=userEvent.setup();render(<XMarketingAdmin initialView="settings"/>);
 const input=await screen.findByDisplayValue('既存');
 await user.click(input);await user.type(input,' 語');
 expect(document.activeElement).toBe(input);expect((input as HTMLInputElement).value).toBe('既存 語');
 await user.click(screen.getByRole('switch',{name:'쿼리 1 활성'}));
 fireEvent.change(screen.getByRole('spinbutton',{name:'우선순위 1'}),{target:{value:'5'}});
 await user.click(screen.getByRole('button',{name:'쿼리 추가'}));
 await user.type(screen.getByRole('textbox',{name:'수집 쿼리 2'}),'  追加  ');
 await user.click(screen.getByRole('button',{name:'쿼리 추가'}));
 await user.click(screen.getByRole('button',{name:'쿼리 3 삭제'}));
 await user.click(screen.getByRole('button',{name:'저장',exact:true}));
 await waitFor(()=>expect(api.updateSettings).toHaveBeenCalledWith({collection_queries:[{query:'既存 語',enabled:false,priority:5},{query:'追加',enabled:true,priority:15}]}));
});
